ecb_codes = {
    'EXR': 'Exchange Rates',
    'EXR1': 'Exchange Rates - Secondary market',
    'EXR2': 'Exchange Rates - Retail market',
    'MIR': 'Money and interest rates',
    'BSI': 'Banking supervision',
    'SEC': 'Securities issues',
    'CLS': 'Collateral',
    'BLS': 'Balance of Payments and International Investment Position Statistics',
    'ICP': 'International Comparison Programme',
    'FVC': 'Financial vehicle corporations',
    'SHI': 'Securities Holdings Statistics',
    'NOM': 'Nominal Cost of Labour',
    'NMD': 'Nominal Money and Banking',
    'FTV': 'Financial Vehicle Corporation Statistics',
    'IFM': 'International Financial Markets',
    'STS': 'Securities Trading Statistics',
    'SEC': 'Securities Issues',
    'MFA': 'Monetary Financial Institutions Interest Rate Statistics',
    'IFS': 'International Finance Statistics',
    'RTS': 'Retail Trade Statistics',
    'ITS': 'International Trade Statistics',
    'BLS': 'Balance of Payments Statistics',
    'MIG': 'Migration Statistics',
    'RIS': 'Residential Property Price Indices',
    'SIS': 'Securities Issuance Statistics',
    'MBS': 'Mortgage Bonds Statistics',
    'SBS': 'Savings Bank Statistics',
    'DSC': 'Deposit Guarantee Schemes',
    'EBS': 'European Banking Sector',
    'SPD': 'Statistical Press Releases - Detailed tables',
    'YLT': 'Youth Labour Market',
    'YEP': 'Young Entrepreneurship',
    'VUE': 'Voluntary Unemployment',
    'WLB': 'Wage Labour Bargaining',
    'WFB': 'Workforce Background',
    'SWS': 'Swiss Wages',
    'SCB': 'Social Costs of Business',
    'LCM': 'Labour Costs for Manufacturing',
    'SEU': 'Small Enterprises in the EU',
    'STG': 'Standardisation in the EU',
    'FRE': 'Free Movement of Workers',
    'FBE': 'Financial and Business Services',
    'CSP': 'Consumer Spending',
    'CLF': 'Community Labour Force',
    'IRN': 'Industrial Relations',
    'YMP': 'Youth Employment',
    'VAC': 'Vacancy Statistics',
    'PTS': 'Public Transport Statistics',
    'COM': 'Competitiveness',
    'CTM': 'Construction and Real Estate',
    'CYM': 'Cycling and Walking',
    'DEM': 'Demographic statistics',
    'DMD': 'Demographic Trends',
    'DCM': 'Demand for Consumer Goods',
    'DAM': 'Digital Commerce',
    'EDM': 'Education and Training',
    'EBR': 'Energy Balance and Renewable Energy',
    'ENV': 'Environment and Energy',
    'ENT': 'Entrepreneurship',
    'EDM': 'Environmental Management',
    'EUC': 'European Union Emissions Trading System',
    'FIS': 'Fisheries',
    'FIN': 'Financial Services',
    'FSD': 'Financial Services in Europe',
    'FAC': 'Foreign Affairs',
    'HEA': 'Health Statistics',
    'HOR': 'Horticulture',
    'HRM': 'Human Resource Management',
    'ICT': 'ICT Statistics',
    'INT': 'International Statistical Cooperation',
    'INV': 'Investment by insurance corporations',
    'IND': 'Industrial Relations',
    'IRA': 'Industrial Raw Material',
    'ISM': 'Internal Market',
    'ISF': 'International Statistical Information',
    'JHA': 'Justice and Home Affairs',
    'JUD': 'Judicial System',
    'JSC': 'Justice and Social Affairs',
    'LAW': 'Law',
    'LEA': 'Leadership',
    'LIT': 'Literature',
    'LNG': 'Languages',
    'MCS': 'Medical Care',
    'MIG': 'Migration',
    'MLG': 'Multilingualism',
    'MED': 'Media',
    'MKM': 'Marketing Management',
    'MKT': 'Market',
    'NRS': 'National Accounts and Regional Statistics',
    'NGA': 'Natural Gas',
    'NGE': 'Natural Environment',
    'NUC': 'Nuclear Energy',
    'NUR': 'Nursing',
    'NCR': 'National Crisis Management',
    'NAM': 'National and Regional Accounts',
    'OPE': 'Operational Programmes',
    'ORG': 'Organisation',
    'PAY': 'Pay',
    'PLA': 'Planning',
    'PAN': 'Pan-European Issues',
    'PER': 'Personal Income Tax',
    'POL': 'Policy and Communication',
    'POP': 'Population',
    'PRI': 'Prices and Costs',
    'PRD': 'Production',
    'PSY': 'Psychology',
    'PTM': 'Public Management',
    'PUB': 'Public Finance',
    'RAT': 'Rating',
    'RET': 'Retail',
    'RUL': 'Rural Development',
    'SCI': 'Science and Technology',
    'SIL': 'Silk',
    'SOC': 'Social Statistics',
    'SPC': 'Sport and Physical Exercise',
    'STA': 'Statistics',
    'SUS': 'Sustainable Development',
    'TAI': 'Taiwan and Japan',
    'TAX': 'Taxation',
    'TEC': 'Technical Information',
    'TOU': 'Tourism',
    'TRA': 'Transport',
    'TRA': 'Trends and Opportunities',
    'VET': 'Veterinary',
    'WAT': 'Water Management',
    'WEL': 'Welfare',
    'WHE': 'Wheat',
    'WIN': 'Wine',
    'WOR': 'World Trade Organization',
    'VOL': 'Volunteering',
    'YOU': 'Youth',
    'ZOO': 'Zoology',
    'ZEB': 'Zero Emission Buildings',
    'ZEU': 'Zero Emissions Units',
    'ZON': 'Zone'
}